---
- name: Windows Feature
  hosts: Windows2019
  gather_facts: true
  tasks:
    - name: Install IIS on Windows Server 2019
      ansible.windows.win_feature:
        name: "Web-Server"
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
    - name: Reboot if installing Web-Server requires it
      ansible.windows.win_reboot:
      when: win_feature.reboot_required
...